### ISSUE TITLE
Pregunta layout: ¿Cómo llegan los productos en la banda transportadora? ¿Individuales o varios en uno?

### ISSUE THREAD

**Issue by ariasAleia** [ART3CHAutomation/WarePatch#31]

**Comment by ChrisCuestas** [comment]
Asumimos que vienen cajas de diferentes tamaños y pesos.

**Comment by ChrisCuestas** [comment]
Individuales, no necesariamente en banda transportadora.
Con disposición ilimitada y en condiciones ideales
