### ISSUE TITLE
Pregunta layout: ¿Qué tipo de productos llegan? ¿Únicamente diferenciados por tamaño?¿Únicamente diferenciados por peso?¿Ambos? Solicitar un ejemplo claro de orden

### ISSUE THREAD

**Issue by ariasAleia** [ART3CHAutomation/WarePatch#33]

**Comment by cychitivav** [comment]
Llegan un solo tipo de producto en 3 tamaños de cajas:

* Grande de $4\ kg$
  ![Box_Size-Grande drawio](https://user-images.githubusercontent.com/30636259/190882118-e41d67bd-c189-4377-b595-51c6530eff0a.svg#gh-light-mode-only)
  ![Box_Size-Grande drawio](https://user-images.githubusercontent.com/30636259/190882128-9f35e6cc-e90a-4589-81b7-c4af84696dee.svg#gh-dark-mode-only)
* Mediano de $2\ kg$
  ![Box_Size-Mediano drawio](https://user-images.githubusercontent.com/30636259/190882148-338a45bd-89a2-42d4-a716-068420cca81a.svg#gh-light-mode-only)
  ![Box_Size-Mediano drawio](https://user-images.githubusercontent.com/30636259/190882159-42bdd81c-95d4-4802-b30d-d76e0dac95d8.svg#gh-dark-mode-only)

* Pequeño de $1\ kg$
  ![Box_Size-Pequeño drawio](https://user-images.githubusercontent.com/30636259/190882196-4d1237d4-80cb-4f73-b019-5c96c8c8789b.svg#gh-light-mode-only)
   ![Box_Size-Pequeño drawio](https://user-images.githubusercontent.com/30636259/190882205-acf66fdf-0228-4ad7-add9-e90996588bd4.svg#gh-dark-mode-only)
