### ISSUE TITLE
Definición de objetivos

### ISSUE THREAD

**Issue by daarojaspa** [ART3CHAutomation/WarePatch#36]
Qué valores objetivo en los indicadores economicos nos gustaria alcanzar y porqué

**Comment by ChrisCuestas** [comment]
Reunión sábado 24 Oct

**Comment by ChrisCuestas** [comment]
Creo que no se podrán definir ahora sin antes de simular el caso base, y ahí si proponer valores objetivo para cada indicador o KPI.
