### ISSUE TITLE
Hacer lista de elementos de la celda robotizada

### ISSUE THREAD

**Issue by ariasAleia** [ART3CHAutomation/WarePatch#43]
Lista preliminar de elementos de la celda:

Máquinas de proceso, manipulador(es), séptimos ejes, elementos de transporte, componentes de control de calidad, otros. No se requieren características técnicas, estás serán definidas para la entrega final del proyecto.

**Comment by cychitivav** [comment]
# Gripper
https://learn.onrobot.com/en/vg10-getting-started?area=8
