### ISSUE TITLE
Simular propuesta sin automatizar en Tecnomatix

### ISSUE THREAD

**Issue by ariasAleia** [ART3CHAutomation/WarePatch#49]
[https://docs.google.com/document/d/1b0qsoK43EjSYeOVO0IlnEftnLFi-jcwI_-gDAVLQh-c/edit](url)

En Tecnomatix se simulará esta propuesta con 2 y 4 clientes con el fin de realizar una comparación, así como un número variable de operarios con el fin de optimizar la solución sin automatizar y tener una propuesta inicial más aproximada a la realidad.

**Comment by ChrisCuestas** [comment]
Carpeta con simulación: [https://drive.google.com/drive/u/0/folders/1j4gBKXQaVS2bLyc0w1aaN7knU_HoxxAF](url)
