### ISSUE TITLE
Montar celda robotizada en Robotstudio

### ISSUE THREAD

**Issue by ariasAleia** [ART3CHAutomation/WarePatch#54]
**Modelar:**
* Cajas

**Añadir:**
* Sistema Robot
* Banda transportadora
* Sistema de alimentación eléctrica
* Puertas
* Componentes de seguridad:
   * Rejas de seguridad

**Comment by cychitivav** [comment]
## Paletizing PowerPac
* https://www.youtube.com/watch?v=w-el0M4Pxgc&t=255s
* https://www.youtube.com/watch?v=P-pxREzQ25w
