### ISSUE TITLE
Documento de conclusiones: ¿Robotizar o no robotizar?

### ISSUE THREAD

**Issue by ariasAleia** [ART3CHAutomation/WarePatch#9]
Documento en grupo (Tarea para el módulo de Celdas robotizadas)
https://classroom.google.com/u/0/c/NDg4NjE4OTg3NTk4/a/NTQ1NzE0MzQyNzA3/details?pli=1

Reunión: ??

Fecha de entrega: Miércoles 14 Sept

**Comment by ariasAleia** [comment]
https://classroom.google.com/u/0/c/NDg4NjE4OTg3NTk4/a/NTQ1NzE0MzQyNzA3/details?pli=1

**Comment by ChrisCuestas** [comment]
Propongo que uno de nosotros se encargue de tomar lo mejor de cada red argumentativa y escribir este documento de conclusiones, como una relatoría. Para evitar consumir tiempo de las reuniones en esto, que poco aporta al proyecto. ¿Qué piensan?
@cychitivav @daarojaspa @jacaballerom3110 @ariasAleia

**Comment by daarojaspa** [comment]
deacuerdo

**Comment by ariasAleia** [comment]
Haríamos entonces cada uno 4 redes argumentativas debido a que hay 4 textos?

**Comment by ChrisCuestas** [comment]
No, @ariasAleia , cada uno hace una red argumentativa, porque toca, el profe dice que eso individual. Entonces serían 5 redes argumentativas, y de estos, debemos sacar un documento de conclusiones.
